{{- if and .Values.backup.enabled (.Values.backup.useLocalBackup) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "netbox.fullname" . }}-backupLocal
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- if .Values.persistence.selector }}
  selector: {{ toYaml .Values.persistence.selector | nindent 4 }}
{{- end }}
{{- end -}}

---
{{- if .Values.backup.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "netbox.fullname" . }}-backupCache
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- if .Values.persistence.selector }}
  selector: {{ toYaml .Values.persistence.selector | nindent 4 }}
{{- end }}
{{- end -}}