{{- if and .Values.backup.enabled (not .Values.backup.existingConfigSecret) }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-backup
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
data:
  config.yaml: |+
{{ .Values.backup.config | toYaml | indent 6 }}
{{- end }}
