{{- if and .Values.backup.enabled (not .Values.backup.existingConfigSecret) }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-backup-secret
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
data:
  config.yaml: {{ include "netbox.tplvalues.render" (dict "value" .Values.backup.config "context" $ ) | toYaml | b64enc | quote }}
  allowRepoCreation: {{ .Values.backup.allowRepoCreation | quote }}
  RepoEncryptionType: {{ .Values.backup.RepoEncryptionType | quote }}
  sshKey: {{ .Values.backup.sshKey | quote }}
  sshKnownHosts: {{ .Values.backup.sshKnownHosts | quote }}
  repoKey: {{ required "repo-key is required" .Values.backup.repoKey | quote }}
  borgPassphrase: {{ required "$BORG_PASSPHRASE is required" .Values.backup.borgPassphrase | quote }}
{{- end }}
