{{- if and .Values.backup.enabled (not .Values.backup.existingConfigSecret) }} 
{{ $requiredDetachedKey := list "keyfile" "keyfile-blake2" }}
{{ $requiredPassphrase := list "repokey" "repokey-blake2" "authenticated" "authenticated-blake2" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-backup-secret
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
data:
  config.yaml: {{ include "netbox.tplvalues.render" (dict "value" .Values.backup.config "context" $ ) | toYaml | b64enc | quote }}
  allowRepoCreation: {{ .Values.backup.allowRepoCreation | quote }}
  repoEncryptionType: {{ .Values.backup.repoEncryptionType | quote }}
  sshKey: {{ .Values.backup.sshKey | quote }}
  sshKnownHosts: {{ .Values.backup.sshKnownHosts | quote }}
  {{- if has .Values.backup.repoEncryptionType $requiredDetachedKey }}
  detachedKey: {{ required "detached-key is required" .Values.backup.detachedKey | quote }}
  {{- end }}
  {{- if has .Values.backup.repoEncryptionType $requiredPassphrase}}
  borgPassphrase: {{ required "borgPassphrase is required" .Values.backup.borgPassphrase | quote }}
  {{- end }}
{{- end }}
