{{- if and .Values.backup.enabled (not .Values.backup.existingConfigSecretRestore) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-backup-secret-restore
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
data:
  restoreBackupName: ""
{{- end }}
