{{- if and .Values.backup.enabled (not .Values.backup.existingConfigSecret) }} 
{{ $requiredDetachedKey := list "keyfile" "keyfile-blake2" }}
{{ $requiredPassphrase := list "repokey" "repokey-blake2" "authenticated" "authenticated-blake2" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-backup-secret
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
data:
  config.yaml: {{ include "netbox.backup.config" . | b64enc | quote }}
  allowRepoCreation: {{ .Values.backup.allowRepoCreation | b64enc | quote }}
  repoEncryptionType: {{ required "repoEncryptionType is required. Possible options are none, authenticated[-blake2], keyfile[-blake2], repokey[-blake2]" .Values.backup.repoEncryptionType | b64enc | quote }}
  sshKey: {{ .Values.backup.sshKey | b64enc | quote }}
  sshKnownHosts: {{ include "netbox.backup.knownhosts" . | b64enc | quote }}
  {{- if has .Values.backup.repoEncryptionType $requiredDetachedKey }}
  detachedKey: {{ required "detached-key is required" .Values.backup.detachedKey | b64enc | quote }}
  {{- end }}
  {{- if has .Values.backup.repoEncryptionType $requiredPassphrase}}
  borgPassphrase: {{ required "borgPassphrase is required" .Values.backup.borgPassphrase | b64enc | quote }}
  {{- end }}
{{- end }}
